GET https://{{baseurl}}/api/identity-management/roles
Content-Type: application/json
Accept-Language: en

###

GET https://{{baseurl}}/api/identity-management/clients
Content-Type: application/json
Accept-Language: en


###

POST https://{{baseurl}}/api/identity-management/clients
Content-Type: application/json
Accept-Language: en

{
  "name": "TestClient",
  "endpoints": [
    "web-app://akka-dmkce-vcmkvmkv-vdnekcenkc"
  ]
}

###

GET https://{{baseurl}}/api/identity-management/clients/63bdb64b-3d8b-4efa-aab8-ee036aa9865a
Content-Type: application/json
Accept-Language: en


###

PUT https://{{baseurl}}/api/identity-management/clients/63bdb64b-3d8b-4efa-aab8-ee036aa9865a
Content-Type: application/json
Accept-Language: en

{
  "name": "TestClient-2",
  "endpoints": [
    "web-app://akka-dmkce-vcmkvmkv-vdnekcenkc"
  ]
}


###

DELETE https://{{baseurl}}/api/identity-management/clients/4c7231d5-b8ee-490b-9bb6-c1680b41d943
Content-Type: application/json
Accept-Language: en


###

GET https://{{baseurl}}/api/identity-management/users
Content-Type: application/json
Accept-Language: en

###

GET https://{{baseurl}}/api/identity-management/users/7a73b4e2-23a2-4416-af43-c28d48ef6482
Content-Type: application/json
Accept-Language: en

###

POST https://{{baseurl}}/api/identity-management/users
Content-Type: application/json
Accept-Language: en

{
  "normalized-email": "test1@example.com",
  "roles": [
    "Reader"
  ],
  "personal-claims": [
    {
      "type": "type1",
      "value": "value1"
    },
    {
      "type": "type1",
      "value": "value2"
    }
  ]
}

###

PUT https://{{baseurl}}/api/identity-management/users/7a73b4e2-23a2-4416-af43-c28d48ef6482
Content-Type: application/json
Accept-Language: en

{
  "normalized-email": "test1@example.com",
  "roles": [
    "Reader"
  ],
  "personal-claims": [
    {
      "type": "type1",
      "value": "value1"
    },
    {
      "type": "type2",
      "value": "value2"
    }
  ]
}

###

DELETE https://{{baseurl}}/api/identity-management/users/7a73b4e2-23a2-4416-af43-c28d48ef6482/recovery-tokens
Content-Type: application/json
Accept-Language: en