GET https://{{baseurl}}/api/identity-management/roles
Content-Type: application/json
Accept-Language: en

###

GET https://{{baseurl}}/api/identity-management/clients
Content-Type: application/json
Accept-Language: en

