GET https://{{baseurl}}/api/identity-management/roles
Content-Type: application/json
Accept-Language: en

###

GET https://{{baseurl}}/api/identity-management/clients
Content-Type: application/json
Accept-Language: en


###

GET https://{{baseurl}}/api/identity-management/users
Content-Type: application/json
Accept-Language: en

###

GET https://{{baseurl}}/api/identity-management/users/7a73b4e2-23a2-4416-af43-c28d48ef6482
Content-Type: application/json
Accept-Language: en

###

POST https://{{baseurl}}/api/identity-management/users
Content-Type: application/json
Accept-Language: en

{
  "normalized-email": "test1@example.com",
  "roles": [
    "Reader"
  ],
  "personal-claims": [
    {
      "type": "type1",
      "value": "value1"
    },
    {
      "type": "type1",
      "value": "value2"
    }
  ]
}