GET http://{{baseurl}}/api/mail-management/attachments


###

GET http://{{baseurl}}/api/mail-management/allowed-languages

###

GET http://{{baseurl}}/api/mail-management/allowed-email-types

###

GET http://{{baseurl}}/api/mail-management/templates

###

GET http://{{baseurl}}/api/mail-management/templates/d6dd2fa4-f14f-4411-98f3-80439566114f/attachments