# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pool: u4.local


variables: 
  BuildNumber: '1.0.0-CI+$(Build.BuildNumber)'

stages: 
- stage: Building
  jobs:
  - job: Restore
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: 'src/Mailer/**/*.csproj'
        feedsToUse: 'select'
  - job: Build 
    dependsOn: Restore
    steps:
    - script: echo BUILD:$(BuildNumber)
    - script: echo BUILD:$(Build.BuildNumber)
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'src/Mailer/Mailer.Api'
  - job: Publish
    dependsOn: Build
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: 'src/Mailer/Mailer.Api'
        arguments: '-c Release  --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
        modifyOutputPath: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathToPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'Mailer'
